/*
 * Data
 */
 
objects = 0x0202063C;
walkrun_state = 0x02037078;
npc_states = 0x02036E38;
stepspeeds = 0x083A719C;
stepspeed_seq_length = 0x083A71B0;

/*
 * Functions
 */

npc_half_reset = 0x08063D1C|1;
npc_set_state_2 = 0x08063CA4|1;
npc_half_reset_when_bit7_is_set = 0x08063D7C|1;
npc_instanciation_something = 0x0805E72C|1;
gf_memcpy = 0x081E5E78|1;
rom_npc_by_local_id_and_map = 0x0805FD5C|1;
sub_805F724 = 0x0805F724|1;

/*
 * Custom Data
 */

follower_state = 0x02031824;
